### ISSUE TITLE
Tracker Ticket

### ISSUE THREAD

**Issue by demhydraz** [swiftOS/sKernel#1]
- [ ] Release 1.0.0

**Comment by demhydraz** [comment]
# Multitasking
- [ ] better isolation
- [ ] block kernel interfaces
- [ ] thread pools
- [ ] dispatch

**Comment by demhydraz** [comment]
# Filesystem
- [ ] /dev
  - [ ] peripherals
  - [ ] specialized devices w/ drivers
  - [ ] network sockets
  - [ ] shared memory

- [ ] /sys
  - [ ] configuration reading
  - [ ] configuration writing

- [ ] metadata
  - [ ] unix permissions
  - [ ] xattr

**Comment by demhydraz** [comment]
# Sandboxing

ties in nicely with the first 2 multitasking goals

- [ ] requests granted by pid1
- [ ] isolate processes from kernel interfaces (apart from pid 1)

**Comment by FlareHAX0R** [comment]
### Symlinking?
- [ ] Check me if this has been added

**Comment by demhydraz** [comment]
Under filesystem maybe idk ಠ_ಠ
